### ISSUE TITLE
[QUESTION] My android app doesn't connect to my chat server.

### ISSUE THREAD

**Issue by xaetacore** [RocketChat/Rocket.Chat.Android#2229] opened 2019-04-16 13:40 UTC
## Description
For some reason my android client does log in but it doesn't load the servers and it says that its disconnected.

I can access the admin panel with the mobile app but i can't send messages or something.
Desktop and Web apps works fine.

## Devices and Versions

Your Rocket.Chat.Android version: 3.3.0
Your Rocket.Chat Server version: 0.74.3

Mobile device model and OS version: Huawei p10 plus Android 9.0.1

## Steps to reproduce

Reinstalling the app on the playstore
Using CloudFlare for SSL

**Comment by Ytheleus** [comment] 2019-04-18 09:02
Same issue with Android client disconnects here. Clients seem to go to disconnected state after going idle. closing/reopening app reconnects. Only started happening after I updated the server a few days ago.

Rocket.Chat Server     0.74.3
Rocket.Chat Android  3.3.0 

Issue is the same on Huawei p20 lite and Samsung Galaxy S8.

**Comment by xaetacore** [comment] 2019-04-18 09:25
I updated my server to allow Websocket connections on apache2 and it seemed to fix the problem for 50%
old channels which are deleted stay on the app and it indeed disconnects for me to when going idle.

i hope there is a fix for this as the web version and desktop version seems to work fine.

**Comment by thawn** [comment] 2019-04-20 17:38
I guess this is a duplicate of bug #2225

**Comment by thawn** [comment] 2019-04-25 08:08
@xaetacore do you mind to post (part of) your apache configuration that (partially) fixed the issue for you here?

**Comment by Ytheleus** [comment] 2019-05-04 21:16
I haven't had this disconnection issue since updating to Android client 3.3.1

**Closed as completed** 2019-07-10 23:26 UTC
