### ISSUE TITLE
[NEW] Support for "iframe auth"

### ISSUE THREAD

**Issue by KyleKotowick** [RocketChat/Rocket.Chat.Android#709] opened 2018-01-22 06:03 UTC
App version: 1.1.0

I have a Rocket.Chat server that uses the ["iframe auth"](https://rocket.chat/docs/developer-guides/iframe-integration/authentication/) option. While this works fine on a web browser (both mobile and computer), it does not work in the Rocket.Chat+ app for Android. When I enter my server's address in the app, it asks me for a username/password, even though that type of authentication is disabled on the server. So, my users cannot use the app. Is support for this feature planned?

**Comment by rafaelks** [comment] 2018-02-08 13:06
@kkotowick We'll support this in our 2.x version, thank you for opening the issue.

**Comment by rafaelks** [comment] 2018-04-03 13:39
This one duplicates #322.

**Comment by rgoerner** [comment] 2019-05-23 18:14
@rafaelks This is not a duplicate of #322 at all.
Oauth integration does not working everytime, like with Jira, or any other custom think which for example needs RSA or any other kind of cert authentication.

What @kkotowick meant was: If you enable your custom Iframe-Login, this is working on any browser (the latest at least...), but not on the App, here, it only loads the very default login screen and this breaks the thing -> if you can not use your custom auth build on a iframe on the App, this iframe-integration is then senseless at all or?

So, is there any plan to fix this thing?

I also mentioned, if you disable password recovery functions, on the browsers, this is disabled, on the App it is then still enabled...

**Comment by Metauriel** [comment] 2019-08-30 08:52
I would be interested in an update about this as well, at the moment our users can not use the app because iframe auth is used on our rocket.chat server.

**Comment by HiveMindNet** [comment] 2020-05-14 21:16
Also interested in this. Any insight that can be shared on what needs to be done to enable mobile app use without enabling default login form or oath, (we wish to only use iframe auth) would be much appreciated.

Thank you

**Comment by diegolmello** [comment] 2020-05-15 12:31
This repo is deprecated: https://github.com/RocketChat/Rocket.Chat.Android#important---please-read-this-first

There's an open issue on the new repo: https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/688

**Closed as completed by diegolmello** 2020-05-15 12:31 UTC
Labels: 🎉 feature

**Comment by HiveMindNet** [comment] 2020-05-15 14:22
> This repo is deprecated: https://github.com/RocketChat/Rocket.Chat.Android#important---please-read-this-first
> 
> There's an open issue on the new repo: [RocketChat/Rocket.Chat.ReactNative#688](https://github.com/RocketChat/Rocket.Chat.ReactNative/issues/688)

Thank you.
