### ISSUE TITLE
Connection refused appli mobile

### ISSUE THREAD

**Issue by jSURF68** [RocketChat/Rocket.Chat.Android#2161] opened 2019-02-25 16:23 UTC
Hi,

I haven't been able to connect to rocket.chat mobile applications for a few days now.

Rocket.chat is installed with Docker with Plesk

Rocket.Chat Version: 0.74.3   
NodeJS Version: 8.11.4 - x64  
Platform: linux                    
Process Port: 3000                   
Site URL: https://chat.adcevents.fr  
ReplicaSet OpLog: Disabled

Do you have any ideas?

Thank you.

**Comment by reetp** [comment] 2019-03-22 16:44
I think this has been fixed - I spent some time with Alexey on open.rocket.chat and we found he had a nginx server he didn't know existed, and it wasn't setup for reverse proxy.

Seems to be OK now.

@alexeyzhuchkov can close this off if he is happy.

**Comment by alexeyzhuchkov** [comment] 2019-03-25 09:08
YES. Thanks very much @reetp @geekgonecrazy .

**Comment by alexeyzhuchkov** [comment] 2019-03-25 09:09
And I'm not able to close the issue, as I'm not the originator of that one.

**Comment by rafaelks** [comment] 2019-03-25 13:06
Thanks guys!

**Closed as completed by rafaelks** 2019-03-25 13:06 UTC

**Comment by geekgonecrazy** [comment] 2019-03-26 05:09
9/10 that’s what the issue is.  Just have to walk through the steps to ensure that is the case. Glad you got it
