### ISSUE TITLE
Rocket.Chat lacks of sharing-feature

### ISSUE THREAD

**Issue by Hans1Hansen** [RocketChat/Rocket.Chat.Android#1681] opened 2018-09-13 18:07 UTC
## Description

It is not possible to share something from another app to the rocket.chat-app, e.g. an interesting link from a webbrowser to a channel in RC 

## Devices and Versions

Your Rocket.Chat.Android version: 2.6
Your Rocket.Chat Server version: 0.67

Galaxy Note 8, Android 8.0

## Steps to reproduce
Open any app on the smartphone with the ability to share to another app: rocket.chat-app is missing as a possible target.

IMHO a very important feature RC should support. Thanks!

**Comment by leonardoaramaki** [comment] 2018-09-25 13:01
I agree, we really need this feature. It's already on our roadmap to include it soon!
Closing this since it's duplicate of #98

**Closed as completed by leonardoaramaki** 2018-09-25 13:01 UTC
