### ISSUE TITLE
Reply text not displaying when send via android client

### ISSUE THREAD

**Issue by alleait** [RocketChat/Rocket.Chat.Android#2475] opened 2019-09-09 07:01 UTC
## Describe the bug
When a reply is sent via the android client the reply tetx does not display . The reply structure shows but there is not reply text in it.

## To Reproduce

1. Sent a message to any user or channel
2. Using the android client reply to that message

## Expected behavior
The reply text should display.

## Screenshots

![image](https://user-images.githubusercontent.com/55078745/64509461-6fb6b000-d2e8-11e9-8a7d-7bdc9bda3e45.png)

## Devices and Versions

Rocket.Chat.Android version: 3.5.1(2077)
Rocket.Chat Server version: 1.3.1

**Comment by philipbrito** [comment] 2019-09-18 01:04
Duplicate of https://github.com/RocketChat/Rocket.Chat.Android/issues/2469

**Closed as completed by philipbrito** 2019-09-18 01:04 UTC
