### ISSUE TITLE
[BUG] Scroll through messages jump to the top

### ISSUE THREAD

**Issue by mmarif4u** [RocketChat/Rocket.Chat.Android#643] opened 2017-12-15 18:50 UTC
Your Rocket.Chat.Android app version: 1.0.33
Phone: Samsung S8

Go to any DM or channel which have hundreds of messages. Scroll though up and at the point where the new messages loads, it jumps to the starting point. Suppose to stay where it is and load the messages for scrolling up. But instead you are left to scroll down to that point where it loaded, quite a hazel.

I am not sure if i explained it properly, hope i did. :)

**Comment by leonardoaramaki** [comment] 2017-12-18 16:56
Thanks for reporting!  :relaxed:
I experienced this and it's very annoying indeed. :disappointed_relieved:
We'll be addressing this anytime soon

**Comment by mmarif4u** [comment] 2017-12-19 06:36
Thanks @leonardoaramaki.

Off-topic: seems like the development for 2.0 is in full swing, is there any ETA for this release(estimated one).

**Comment by rafaelks** [comment] 2017-12-20 12:58
@mmarif4u There's no estimate yet, but we do plan to have something "usable" by Jan 15th.

**Comment by cbcdevops** [comment] 2018-01-04 16:41
Here are steps to reproduce this:

1. Open Android mobile app
2. Select a different channel than the one you are currently on
3. Drag the messages down a little, once or twice
// expected:  you'll scroll up a little
// actual: after a moment it will scroll way far up, maybe halfway up the history or more.
// now you have to scroll way back down
// Note that step 2 seems to be necessary to reproduce.   Once you have done some successful scrolling in a channel, you won't have the problem in that channel while you remain in it.

**Comment by rafaelks** [comment] 2018-03-13 09:28
Closing now, because it's already implemented in [2.0.0](https://github.com/RocketChat/Rocket.Chat.Android/milestone/6).

**Closed as completed by rafaelks** 2018-03-13 09:28 UTC
Labels: :bug: bug
