### ISSUE TITLE
Text disappear on rtl system language

### ISSUE THREAD

**Issue by adispi** [RocketChat/Rocket.Chat.Android#1709] opened 2018-09-29 12:35 UTC
## Description

On Android that is set to Hebrew on system language (rtl) the texts in the chat is gone. 
You have a line with the image of the user for each chat try, however, no text at all.
If you change the system language on Android to English the text reapear.

## Devices and Versions
Android 8.1 on Nexus 6p.
Version 2.6.1

Your Rocket.Chat.Android version: (e.g. 2.1.0)
Your Rocket.Chat Server version: (e.g. 0.63.1-develop)

Mobile device model and OS version: (e.g. "Nexus 7 - Android 6.0.1")

**Comment by leonardoaramaki** [comment] 2018-10-01 16:49
Duplicate of #1679

**Closed as completed by leonardoaramaki** 2018-10-01 16:49 UTC
