### ISSUE TITLE
F-Droid not updating

### ISSUE THREAD

**Issue by martinszy** [RocketChat/Rocket.Chat.Android#2339] opened 2019-05-23 18:49 UTC
The f-droid listing is stuck in version 3.2.0, but the metadata is updated to 3.4.1

Public listing in F-Droid: https://f-droid.org/en/packages/chat.rocket.android/

Metadata: https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/chat.rocket.android.yml#L167

Maybe related to #2179

**Comment by Perflyst** [comment] 2019-05-25 19:13
Duplicate of #2250

**Closed as completed** 2019-06-04 17:29 UTC
