### ISSUE TITLE
User status always stays onlkne

### ISSUE THREAD

**Issue by ccfiel** [RocketChat/Rocket.Chat.Android#573] opened 2017-11-15 05:35 UTC
User status always says online (green) even the user is idle or offline.

**Comment by mmarif4u** [comment] 2017-11-15 06:21
I can confirm that. It do show correct status in the members list but in the sidebar menu it shows wrong status for each user.

**Comment by leonardoaramaki** [comment] 2017-11-16 20:12
@mmarif4u Do you still get this issue on the sidebar? It's supposed to be solved already. If you are experiencing this specific issue I'd like to ask you to open another issue describing how to reproduce it.

**Comment by leonardoaramaki** [comment] 2017-11-16 20:15
@ccfiel I had myself this issue with one of my test users. It got stuck on the online status. It's on the queue to investigate but I suspect something went really wrong on server-side. I'll be talking to the guys as soon as I can about that.

**Comment by mmarif4u** [comment] 2017-11-17 15:26
@leonardoaramaki i can create another issue if needed, but i feel it is the same issue which i just noticed too. Example screens for your ref.

The member list shows almost correct statuses excluding one(mine) which is yellow, which is suppose to be green(see the next screen).
![screenshot_20171117-230032](https://user-images.githubusercontent.com/1280585/32954528-5393a6d8-cbee-11e7-897f-71c04ab89e60.png)
![screenshot_20171117-230038](https://user-images.githubusercontent.com/1280585/32954529-53c81648-cbee-11e7-9ae9-82187a855604.png)

**Comment by rafaelks** [comment] 2018-03-13 09:27
Closing now, because it's already "fixed" in [2.0.0](https://github.com/RocketChat/Rocket.Chat.Android/milestone/6).

**Closed as completed by rafaelks** 2018-03-13 09:27 UTC
Labels: :bug: bug, 🕵️ investigate
