### ISSUE TITLE
App does not login

### ISSUE THREAD

**Issue by Syirrus** [RocketChat/Rocket.Chat.Android#49] opened 2016-11-25 00:34 UTC
Your Rocket.Chat.Android version: (make sure you are running the latest)

When I run the application and try to login (after pushing the arrow button) it does nothing. It doesn't log in at all. My installation of rocket.chat works just fine in Cordova or on the Web.

**Comment by laggedHero** [comment] 2016-11-25 15:18
@Syirrus The new Android app is been build upon the new version of the Rocket.Chat API. That may be the cause of your bug.

And if that's the case I would ask you to wait for the release of the new API. I don't think that back supporting the old API is something we'll be doing.

**Comment by maxlinux2000** [comment] 2016-12-18 15:30
same issue here.... I just install the last version of rocket.chat by snap (0.48.1) and build the last version of rocket.chat-android
From the web I can login on my rocket.chat installation using https and from rocket.chat.cordova too, but I can't from the native app to same server.

I can see a message like "Connection timeout"

but from native app, I can login on demo.rocket.chat without problems.... why?

how can I debug it? I tried with Chrome Inspector but nothing...

**Comment by geekgonecrazy** [comment] 2016-12-18 17:55
Can you verify you are letting websockets through?  Open chrome inspector in your browser and look for a websockets connection.  

If you can't connect via websockets I don't think this app will work. Where as the other app will

**Comment by maxlinux2000** [comment] 2016-12-18 18:01
Ok, tomorrow I will have a look about it

**Comment by laggedHero** [comment] 2016-12-19 17:46
@geekgonecrazy @maxlinux2000 The native app will be compatible with the server version 0.49.0 and up.

If you would like to try it, look at `0.49.0-develop`.

**Comment by geekgonecrazy** [comment] 2016-12-19 17:48
@laggedHero 👍  if websocket passthrough isn't allowed this will also cause it not work right?

**Comment by laggedHero** [comment] 2016-12-19 17:50
@geekgonecrazy on top of websocket we need the newer API available on 0.49.0. So, yeah, that's right. :)

**Comment by laggedHero** [comment] 2016-12-19 17:53
Guys: I'll be closing this issue. I just added #90 in order to improve this situation.

We won't be adding support for the current (as of 0.48.x) API.

**Closed as completed by laggedHero** 2016-12-19 17:53 UTC
