### ISSUE TITLE
[NEW] Starred messages list

### ISSUE THREAD

**Issue by reetp** [RocketChat/Rocket.Chat.Android#1112] opened 2018-04-18 09:37 UTC
Your Rocket.Chat.Android version:
2.0.1
Rocket version 0.63.1 - Docker install

Phone:

Samsung S6 - Android 7.0

With the new app I can see Pinned messages, but Starred messages are not available?

**Comment by rafaelks** [comment] 2018-04-18 14:35
Changed to a feature, it's not a bug. 👍

**Comment by reetp** [comment] 2018-04-18 14:50
LOL.....
Starred messages appear in the desktop app and browser. They are used.
They DID appear in the old app.
So the functionality has been lost, removed, or broken (especially as the update was effectively forced)
That's a bug not a feature. I digress.

**Comment by leonardoaramaki** [comment] 2018-04-19 15:49
@reetp I think what @rafaelks meant is that this feature not appearing on 2.0.0 onwards is something new to the redesign so in order for us to best organize our tasks it fits better as a *new* feature to the redesigned app.
Moreover, starring messages is still up to debate if we should include or deprecate it.

**Comment by divyanshub024** [comment] 2018-04-19 15:55
We also have pin message functionality. You can pin your messages.

**Comment by rafaelks** [comment] 2018-04-19 16:44
@reetp In order to fully support star/unstar messages, we need some changes in our APIs and improve the way it is handled, because today is a mess. That's why we didn't implement it yet. I'll let this issue opened for now and we'll discuss what do to about it. Thank you!

**Comment by reetp** [comment] 2018-04-21 10:11
I get all the comments.
Just frustrating that having had the use of starred messages, and messages being starred, it is not possible to see them now.
So we have the option if going through them and converting to pinned, or not being able to see them on mobile.
I'll keep watch for developments :-)

**Comment by leonardoaramaki** [comment] 2018-04-27 23:44
Closing this due to duplicate of https://github.com/RocketChat/Rocket.Chat.Android/issues/1009.

**Comment by reetp** [comment] 2018-04-27 23:57
This not a dupe of #1009 which refers to starring Rooms

This references starred Messages in rooms.

Please reopen.

**Comment by leonardoaramaki** [comment] 2018-04-28 00:02
Yeah, you're right. There are about three different issues relating to favoriting things, I think I got dizzy.

**Comment by reetp** [comment] 2018-04-28 12:03
LOL - know that feeling ;-)
Thanks

**Closed as completed** 2018-05-16 18:51 UTC
Labels: 🎉 feature
