### ISSUE TITLE
OAUTH 2FA app on same phone - completely broken

### ISSUE THREAD

**Issue by adam-kulagowski** [RocketChat/Rocket.Chat.Android#293] opened 2017-05-20 08:32 UTC
Rocket.Chat.Android version: 1.0.11

While doing 2FA Google OAUTH , any switch to the other android app (to receive SMS with the code or to generate OTP by myself) reset the whole process to the start. I have to enter login, password again. IT is repeatable  on any device we have tried.

**Comment by geekgonecrazy** [comment] 2017-05-20 15:18
Must be loosing the state much like was happening with #256

**Comment by rafaelks** [comment] 2017-05-22 12:15
Good catch, will address it as a bug to be fixed (cc @matheusjardimb).

**Comment by Sing-Li** [comment] 2017-05-24 03:57
@adam-kulagowski   Thank you!   I was *just* about to add an issue myself.   

EXACTLY the same bug has completely disabled GitHub 2FA login for me.    And GitHub 2FA is *very* important to us, being an open source coding project.

Basically, if anyone use Authy 2FA App (2nd factor code generator) on the same Android phone - switching to Authy will immediately reset the login sequence.  And one ends up SOL.   

This bug would prevent use of any 2FA authenticator app on the same phone  😞

**Comment by matheusjardimb** [comment] 2017-05-31 02:23
Sorry guys, but it either I didn't reproduced it correctly or it got fixed by another issue. 

Steps I've done:
- create a new user (browser) and setup 2FA using Google 2FA Android app.
- fresh installed RocketChat+ and provided server, user and password
- when asked to inform OTP, minimized RC+ app and opened Google 2FA again. Then minimized Google 2FA, and re-opened RC⁺

Result:
- RC+ remained in the expected screen (waiting for OTP). And after providing OTP, I could login without problems.

The only way I found to force lose progress (repeat username/pwd) is to kill the app instead of minimizing it. But I really see that behavior as expected.

Can you guys try to reproduce it again with the develop branch version? If that's not possible, there must be an update into GooglePlay in the near future.

BTW: I've notice that the keyboard for entering OTP isn't "number-only". I'll submit a PR to fix that :smile:

**Comment by matheusjardimb** [comment] 2017-05-31 02:41
From:
![device-2017-05-30-233412](https://cloud.githubusercontent.com/assets/468794/26613493/652b2f4e-4591-11e7-8ea0-e168ac266810.png)
To:
![device-2017-05-30-233734](https://cloud.githubusercontent.com/assets/468794/26613495/6584cb80-4591-11e7-9603-2ec0033aa256.png)

**Comment by adam-kulagowski** [comment] 2017-05-31 03:38
@matheusjardimb : I think that the fastest way would be to provide *apk file. Either here on Github release page or via Google Play.

Otherwise I will try in the following days to setup all tool to build the app by myself.

**Comment by matheusjardimb** [comment] 2017-05-31 23:42
Sure! @adam-kulagowski  here is the most recent apk file. 
Please uninstall your current version and test against this one. Thanks a lot! 

[app-debug_v1.0.13.apk.zip](https://github.com/RocketChat/Rocket.Chat.Android/files/1043203/app-debug_v1.0.13.apk.zip)

If the problem continues, also provide your Android version and device name.

**Comment by geekgonecrazy** [comment] 2017-06-01 02:26
Just verified that it works on the latest from develop.  If you already have official one installed from the play store you can install this one: [here](https://716-48179404-gh.circle-artifacts.com/0/tmp/circle-artifacts.WvtGq2a/app-release.apk) its signed the same as release and will install over top of existing

**Comment by matheusjardimb** [comment] 2017-06-01 02:30
Thanks, @geekgonecrazy! That's awesome :)

So, I'll close this issue and merge #299.

Let me know if any of you guys are still able to reproduce the issue with different use cases.

**Comment by adam-kulagowski** [comment] 2017-06-01 16:01
Unfortunately the bug is still there for me.
I'm using MotoG xt1039
FW: LineageOS 14.1 (android 7.1.2)

I'll try tomorrow on different phone.

**Comment by Sing-Li** [comment] 2017-06-01 17:15
Thanks for the fix, @matheusjardimb 

But it did not fix the problem for me.  Although the delay before resetting is now longer after I switch back to the 2FA code entry on GitHub (still way too short to enter the code though).

Phone is Asus Zenfone 3 Laser  ASUS_Z01BDC
FW: Android 7.0

I am using GitHub 2FA  with Authy (app) as the code generator.

BTW - also using @geekgonecrazy 's  easy-install side-loaded APK

**Comment by matheusjardimb** [comment] 2017-06-02 03:04
@Sing-Li: it seems to me the problem you are reporting is different than the one that originated this issue. How does Github relates to the RC+ app? Can you detail further the steps you are taking?

I may have misunderstood the issue, but it seemed to be a matter of user having to enter username/pwd twice when switching from RC+ and Google 2FA. Am I missing something? 

I've tested with Android 6.0 and 7.0 and couldn't reproduce the issue. I try again tomorrow with an v7.1.

Thanks for your help!

**Comment by Sing-Li** [comment] 2017-06-02 03:15
@matheusjardimb   Yes. I think it may be the same problem. (but related to using GitHub 2FA to login instead of Google 2FA).

>  may have misunderstood the issue, but it seemed to be a matter of user having to enter username/pwd twice when switching from RC+ and Google 2FA. Am I missing something?

I use GitHub OAUTH to log onto Rocket.Chat.

The problem is the generated 2FA code is only valid for a few seconds.  

By the time you enter the username and password again (because it is reset when you switch back), the 2FA code will have expired.   

The easiest way to see or reproduce this is:

0) setup GitHub account for 2FA
1) install authy app on your android phone
2) use authy instead of Google Authenticator for your GitHub 2FA
3) try to (GitHub OAuth) authenticate using  Rocket.Chat+ on the same phone that you have authy installed

Thanks again.

**Comment by adam-kulagowski** [comment] 2017-06-02 03:39
Unfortunately the bug is still there for me.
I'm using MotoG xt1039
FW: LineageOS 14.1 (android 7.1.2)

I'll try tomorrow on different phone.

**Comment by geekgonecrazy** [comment] 2017-06-02 04:46
Ah!  I think I see where the gap in communication is occuring.

I think the issue is when signing in via Google / GitHub and other SSO.  When you use a Google account for instance that requires 2FA.  When you switch to the Google Authenticator app or Authy the app seems to lose track of the ongoing sign in via Google or GitHub.

The issue fixed was when using 2FA recently added to Rocket.Chat not this one.

So this is about Android app being backgrounded while signing into a Google account that has 2FA enabled and backgrounding the app to get code.

This I was able to replicate.

Please correct me if I'm wrong guys :)

**Comment by Sing-Li** [comment] 2017-06-02 12:15
@geekgonecrazy Yes.  Precisely.  Thanks for confirming.

**Comment by matheusjardimb** [comment] 2017-06-03 13:28
@geekgonecrazy exactly!! I was testing a different path! :D 
@Sing-Li I was testing 2FA without using Github.

Now I'm able to reproduce it too! I'll start working on it ;)

**Comment by matheusjardimb** [comment] 2017-06-03 16:18
@Sing-Li @geekgonecrazy @adam-kulagowski 
PR 302 must have fixed this issue. I was able to login using Github and Google (both with 2FA). Also, tested regular username/pwd and had no side-effect.

You can get an apk from ci, [clicking here](https://726-48179404-gh.circle-artifacts.com/0/tmp/circle-artifacts.FdWlEjx/app-release.apk) 

Hope it's fixed now :smile:

**Comment by Sing-Li** [comment] 2017-06-03 16:59
@matheusjardimb   YES!!!  :Dancing-Bananas:   :Big-Hug:    

Thank you for the magical #302 !

The APK did indeed fixed this showstopper (like, I cannot login to my account using the app ! ...) for me.

@adam-kulagowski  Please verify that the problem is fixed on _all_ your phones as well.

Thanks again @matheusjardimb.

**Comment by adam-kulagowski** [comment] 2017-06-03 20:03
@matheusjardimb  - Fixed :)

**Closed as completed** 2017-06-03 20:30 UTC
Labels: :bug: bug
